version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin:5.1.0-fpm-alpine
    restart: always
    ports:
      - 8085:80
    environment:
      - PMA_ARBITRARY=1